# Generated by Django 5.0.1 on 2024-01-27 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile',
            field=models.ImageField(default=datetime.datetime(2024, 1, 27, 16, 29, 30, 461855, tzinfo=datetime.timezone.utc), upload_to='static/images'),
            preserve_default=False,
        ),
    ]
